#!/bin/bash

if [ $# -ne 0 ]; then
    exit 1;
fi

LN_CMD="$( which ln ) -sivb"
LN_HOME_DIR="$( dirname $( readlink -f "${0}" ) )/home"

lnif ()
{
    local -r target="${1}"
    local -r file="${2}"
    local -r link_name="${target}/$( basename "${file}" )"

    if [ "$( readlink -f "${link_name}" )" != "${file}" ]; then
        ${LN_CMD} -t "${target}" "${file}"
    else
        echo "'${link_name}' is already setup"
    fi
}

echo "1 :: FILES"
for file in $( find "${LN_HOME_DIR}" -maxdepth 1 -mindepth 1 -type f ); do
    lnif "${HOME}" "${file}"
done

echo
for dir in $( find "${LN_HOME_DIR}" -maxdepth 1 -mindepth 1 -type d ); do
    subdir="${HOME}/$( basename "${dir}" )"
    echo "2 :: DIRECTORIES :: ‘${subdir}’"
    mkdir -v "${subdir}"
    for file in $( find "${dir}" -maxdepth 1 -mindepth 1 -type f ); do
        lnif "${subdir}" "${file}"
    done
done
